### ISSUE TITLE
Invalid db schema detected

### ISSUE THREAD

**Issue by HcsOmot** [zgphp/joindin-raffler-backend#107]
**Running ```doctrine:schema:validate``` reports violations in schema:**
```
The association App\Entity\JoindInComment#user refers to the inverse side field App\Entity\JoindInUser#comments which does not exist.
```

**Comment by devboard-test** [comment]
I would suggest adding the comments property on JoindInUser, seems I forgot to add one :(

BTW. we could also run `doctrine:schema:validate` on each circle build and we will notice those stupid errors when they happen

**Comment by HcsOmot** [comment]
Just a heads-up: I'm splitting this issue into two - pt.2 (reverting migrations) will be a new, separate issue.
