### ISSUE TITLE
Populate admin with users

### ISSUE THREAD

**Issue by msvrtan** [zgphp/joindin-raffler-backend#166]
We should administer users via admin

**Comment by HcsOmot** [comment]
If we can somehow use easyadmin to create new users (fos:user), maybe that could help closing #169 and #163)

**Comment by HcsOmot** [comment]
We can create a new user record using easyadmin, but the newly created user cannot log in.
Easyadmin writes a plain text password directly into the db, bypassing fos:user password hashing.

Proposed solution:
 - create a custom registration form for creating new admin users
 - use fos:usermanager to create the new user with provided credentials
 - protect the route
 - add menu item to easyadmin backend

Ping @msvrtan for comment.
