### ISSUE TITLE
[BUG] Sync with joind.in throws an error

### ISSUE THREAD

**Issue by msvrtan** [zgphp/joindin-raffler-backend#184]
Seems like https://zgphp-joindin-raffler-staging.herokuapp.com/api/joindin/fetch/all is not running all the way. From running each sync manually, same thing happens on https://zgphp-joindin-raffler-staging.herokuapp.com/api/joindin/comments/fetch so the bug is somewhere in there ...

@HcsOmot can you look it up over weekend?

**Comment by HcsOmot** [comment]
Sure, I'll take a look. Hopefully it's nothing major.
